# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e0ad7267678aca736d6a5a35db21a7af34fd8cf52da3b99ade71fd251346ab462752dd88867ad75f37f02c653d52ca2cdf2077e20c7a9471b61b1187d28f776

test:
  secret_key_base: fa3c8bf358ed60a6a387b44a75e6cddd5949b1cf9f30de25a1f3ee0e99dec42a78ae327b9d64fd19f1c6f98d2e1eedfebca1efc78361ad78747c2e2103bf996c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
