# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45b3d8b9dfe59ddb4f259f18f52b714093eef3a8b829e1c866a446a9668f91c6099fe6824d94ccd3bfe0c28e7333da19688a179cc5c6df83e8f9e76f3a66d38d

test:
  secret_key_base: 354edd1cc0a1507763f1e46b9d92689deda7c71cf34ae5b60c0a6cac173edd1682ad7c51cdf97557aab8c757d844a03c31552c6065164accfca54f4f0ea32b86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
